id: P7D3BDBAC
initial_creation_type: input
source_metadata:
  title: Sakya Paṇḍita Series
  language: pt
  description: 'A series of texts by and about the great scholar Sakya Paṇḍita Kunga
    Gyaltsen (kun dga'' rgyal mtshan, 1182–1251):'
  volume:
    1a141a00adf1443688e715424d2d4535:
      title: A Wondrous Instruction for the Moment of Death
      parent: Advice
    69fa7d4bdac5454caaef276b0dc4dcf9:
      title: Meditation on Amitābha
      parent: Advice
    fe180b64ef064eb9b61f02a02ca34225:
      title: Verses of Aspiration to Recite While Prostrating
      parent: Aspiration Prayers
    966892c0f914447a8ae2c56413d46062:
      title: The Gaṇacakra Ritual
      parent: Commentaries
    9d8a50541eff48d59c0a14c96c6cfda7:
      title: 'Rain of Wisdom, Love and Spiritual Power: A Guru Yoga of the Three Mañjughoṣas
        of the Land of Snow'
      parent: Guru Yoga
    00062c01a63748b08c1fc77422d26ed5:
      title: 'The Sun of Ambrosial Wisdom: A Guru Yoga of Dharmarāja Sakya Paṇḍita'
      parent: Guru Yoga
    3d8c695878f1474f9c34fc132fb2e177:
      title: Sakya Paṇḍita’s Instruction on Parting from the Four Attachments
      parent: Mind Training
    6c50e1128f524691a74b95f08bdb0215:
      title: Praise to Sakya Paṇḍita
      parent: Praise
    c8bbba2b67bc40ad891b7d3c02c64f4a:
      title: Prayer to Invoke the Wisdom Mind of the Gentle Protector Sakya Paṇḍita
      parent: Prayers
created_at: '2022-03-01T01:26:41.732819'
last_modified_at: '2022-03-01T01:26:41.732821'
